esp32:
  board: lolin_c3_mini
  # variant: esp32c3
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

# OTA is required for Over-the-Air updating
ota:
  - platform: esphome
    id: ota_esphome

wifi:
  # Enable for Wemos C3 mini v1.0.0
  output_power: 8.5

light:
  - platform: status_led
    id: _status_led
    name: "Status"
    pin:
      number: GPIO7
      inverted: True
    internal: True

binary_sensor:
  - platform: gpio
    id: boot_button
    pin:
      number: GPIO9
      mode:
        input: True
        pullup: True
      inverted: True
      ignore_strapping_warning: True
    internal: True
