esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

# OTA is required for Over-the-Air updating
ota:
  - platform: esphome
    id: ota_esphome

wifi:
  min_auth_mode: WPA2

light:
  - platform: status_led
    id: _status_led
    name: "Status"
    pin:
      number: GPIO2
      inverted: True
    internal: True

binary_sensor:
  - platform: gpio
    id: boot_button
    pin:
      number: GPIO0
      mode:
        input: True
        pullup: True
      inverted: True
    internal: True
