binary_sensor:
  - id: !extend boot_button
    filters:
      - delayed_on: 50ms 
    on_multi_click:
      - timing:
          - ON for 0.2s to 3s
          - OFF for 0.1s to 2s
          - ON for 0.2s to 3s
          - OFF for 0.1s to 2s
          - ON for at least 5s 
        then:
          - repeat: 
              count: 5
              then:
                - light.turn_on: _status_led
                - delay: 150ms
                - light.turn_off: _status_led
                - delay: 150ms
          - light.turn_on: _status_led
          - button.press: factory_reset_button

button:
  - platform: factory_reset
    id: factory_reset_button
    internal: True
