packages:
  # Include all of the core configuration
  core: !include livingcolors1-cc2500-shieldv2-d1mini.yaml
  factory_reset: !include factory_reset.yaml

esphome:
  # This will allow for project identification,
  # configuration and updates.
  project:
    name: rrooggiieerr.livingcolors1-cc2500-shieldv2-d1mini
    version: dev # This will be replaced by the github workflows with the `release` version

# This points to the public location of the yaml file that will be adopted.
# In this case it is the core yaml file that does not contain the extra things
# that are provided by this factory yaml file as the user does not need these once adopted.
dashboard_import:
  package_import_url: github://rrooggiieerr/esphome-livingcolors1/livingcolors1-cc2500-shieldv2-d1mini.yaml@main

# Sets up the improv via serial client for Wi-Fi provisioning.
# Handy if your device has a usb port for the user to add credentials when they first get it.
improv_serial:
  next_url: https://github.com/rrooggiieerr/esphome-livingcolors1

# Used to pull OTA updates
http_request:
  verify_ssl: false

ota:
  - platform: http_request
    id: ota_http_request

update:
  - platform: http_request
    name: None
    id: update_http_request
    source: https://github.com/rrooggiieerr/esphome-livingcolors1/releases/latest/download/livingcolors1-cc2500-shieldv2-d1mini.manifest.json
